server:
  port: 10010
spring:
  application:
    name: mi-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${server.port}
zuul:
#  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    mi-user:
      path: /user/**
      service-id: mi-user
    mi-goods: /goods/**
    mi-cart: /**
    mi-ad: /**
    mi-sms: /**
  add-host-header: true
  sensitive-headers:  #设置zuul的过滤头为空（所有的头信息全部展示）
ribbon:
  ConnectTimeout: 3000 # 连接超时时间(ms)
  ReadTimeout: 3000 # 通信超时时间(ms)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 20000 # 熔断超时时长：10000ms