server:
  port: 12000
spring:
  application:
    name: mi-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/luomoo/mi_dev.git
  rabbitmq:
    host: 192.168.211.135
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

