server:
  port: 10086
spring:
  application:
    name: mi-eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false
    fetch-registry: false